# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clicktale}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Railsware LLC"]
  s.date = %q{2010-03-31}
  s.description = %q{Use ClickTale (http://www.clicktale.com/) analytics service with rails sites that require sessions (user authentication for example)}
  s.email = %q{al@railsware.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "clicktale.gemspec",
     "init.rb",
     "lib/clicktale.rb",
     "lib/clicktale_helper.rb",
     "spec/clicktale_helper_spec.rb",
     "spec/clicktale_spec.rb",
     "spec/lib/attribute_accessors.rb"
  ]
  s.homepage = %q{http://github.com/railsware/clicktale}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Use ClickTale analytics service with rails sites that require sessions}
  s.test_files = [
    "spec/clicktale_helper_spec.rb",
     "spec/clicktale_spec.rb",
     "spec/lib/attribute_accessors.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

